AIR_DENSITY = 1.3	#[kg/m3]

DRAG_COEFF = 0.7	#[-]
DRAG_INTEGRAL = 0.45 # [-]

INFLATION_CANOPY_FILL_CONST	= 5 #[-]
DECCELERATION_EXPONENT = 0.85	#[-]

OPENING_LOAD_SHOCK_FACTOR = 1.6 #[-]
OPENING_FORCE_REDUCTION_FACTOR = 0.9 #[-]

G_ACCELERATION = 9.81 #[m/s**2]